name: Build README PDF

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 1: Generate the PDF using the default, reliable command.
      # This will create a file named README.pdf.
      - name: Generate PDF with default name
        run: npx md-to-pdf README.md

      # Step 2: Rename the generated file to your desired name.
      - name: Rename PDF to notebook.pdf
        run: mv README.pdf notebook.pdf

      # Step 3: Commit the final, correctly named file.
      - name: Commit and push PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate PDF from README.md"
          file_pattern: notebook.pdf # Commit the renamed file
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
